<?php

declare(strict_types=1);

namespace App\Domains\Security\Enums;

enum ActivityType: string
{
    case ACCESS_DENIED = 'ACCESS_DENIED';
    case ATTACHMENT_DELETED = 'ATTACHMENT_DELETED';
    case ATTACHMENT_DOWNLOADED = 'ATTACHMENT_DOWNLOADED';
    case ATTACHMENT_PERMISSION_DENIED = 'ATTACHMENT_PERMISSION_DENIED';
    case ATTACHMENT_SIZE_EXCEEDED = 'ATTACHMENT_SIZE_EXCEEDED';
    case ATTACHMENT_UPLOADED = 'ATTACHMENT_UPLOADED';
    case ATTACHMENT_VIRUS_DETECTED = 'ATTACHMENT_VIRUS_DETECTED';
    case CSRF_ATTACK_BLOCKED = 'CSRF_ATTACK_BLOCKED';
    case IP_BLOCKED = 'IP_BLOCKED';
    case IP_UNBLOCKED = 'IP_UNBLOCKED';
    case LOGIN_FAILED = 'LOGIN_FAILED';
    case LOGIN_SUCCESS = 'LOGIN_SUCCESS';
    case LOGOUT = 'LOGOUT';
    case PASSWORD_CHANGED = 'PASSWORD_CHANGED';
    case POST_CREATED = 'POST_CREATED';
    case POST_DELETED = 'POST_DELETED';
    case POST_PINNED = 'POST_PINNED';
    case POST_UNPINNED = 'POST_UNPINNED';
    case POST_UPDATED = 'POST_UPDATED';
    case POST_VIEWED = 'POST_VIEWED';
    case SECURITY_ACTIVITY_SCAN_COMPLETED = 'SECURITY_ACTIVITY_SCAN_COMPLETED';
    case SQL_INJECTION_BLOCKED = 'SQL_INJECTION_BLOCKED';
    case SUSPICIOUS_ACTIVITY_DETECTED = 'SUSPICIOUS_ACTIVITY_DETECTED';
    case USER_REGISTERED = 'USER_REGISTERED';
    case XSS_ATTACK_BLOCKED = 'XSS_ATTACK_BLOCKED';
}
