version: '3.8'

services:
    nginx:
        image: nginx:latest
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
            - ./docker/nginx/ssl:/etc/nginx/ssl
            - ./public:/var/www/html/public
            - ./storage/app/public:/var/www/html/public/storage
        depends_on:
            - php
        networks:
            - app-network

    php:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379
        depends_on:
            - redis
        networks:
            - app-network

    redis:
        image: redis:alpine
        ports:
            - '6379:6379'
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
