version: '3.8'

services:
    php:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        environment:
            APP_ENV: production
            DB_CONNECTION: sqlite
            DB_DATABASE: /var/www/html/database/database.sqlite
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
