services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile.production
            target: base # 生產環境使用 base stage
        volumes:
            # 僅掛載必要的資料目錄
            - ./storage:/var/www/html/storage
            - ./database:/var/www/html/database
        environment:
            APP_ENV: ${APP_ENV:-production}
            APP_DEBUG: ${APP_DEBUG:-false}
            APP_URL: ${APP_URL}
            DB_CONNECTION: ${DB_CONNECTION:-sqlite}
            DB_DATABASE: ${DB_DATABASE:-/var/www/html/database/database.sqlite}
            SESSION_LIFETIME: ${SESSION_LIFETIME:-120}
            CSRF_TOKEN_LIFETIME: ${CSRF_TOKEN_LIFETIME:-120}
            UPLOAD_MAX_SIZE: ${UPLOAD_MAX_SIZE:-10M}
            UPLOAD_MAX_FILES: ${UPLOAD_MAX_FILES:-10}
            STORAGE_PATH: ${STORAGE_PATH:-/var/www/html/storage/files}
        networks:
            - app-network
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "php-fpm", "-t"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 30s
        # 安全性設定
        security_opt:
            - no-new-privileges:true
        cap_drop:
            - ALL
        cap_add:
            - CHOWN
            - SETGID
            - SETUID

    nginx:
        image: nginx:alpine
        volumes:
            - ./docker/nginx/nginx-production.conf:/etc/nginx/conf.d/default.conf:ro
            - ./public:/var/www/html/public:ro
        ports:
            - "${NGINX_PORT:-80}:80"
        depends_on:
            - php
        networks:
            - app-network
        restart: unless-stopped
        # 安全性設定
        security_opt:
            - no-new-privileges:true
        cap_drop:
            - ALL
        cap_add:
            - CHOWN
            - SETGID
            - SETUID

networks:
    app-network:
        driver: bridge
