services:
    php-test:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            target: test
        volumes:
            - .:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./storage/logs:/var/www/html/storage/logs
            - ./storage/cache:/var/www/html/storage/cache
            - ./storage/coverage:/var/www/html/storage/coverage
        environment:
            APP_ENV: testing
            DB_CONNECTION: sqlite
            DB_DATABASE: ':memory:'
            PHP_IDE_CONFIG: 'serverName=Docker'
            XDEBUG_MODE: coverage
            XDEBUG_CONFIG: 'client_host=host.docker.internal'
        healthcheck:
            test: ['CMD', 'php', '-v']
            interval: 10s
            timeout: 5s
            retries: 3
        command: >
            bash -c "
                mkdir -p storage/coverage storage/logs storage/cache &&
                chmod -R 777 storage &&
                ./vendor/bin/phpunit --testsuite unit,integration --coverage-html ./storage/coverage --coverage-text"
