version: '3.8'

services:
    php:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        networks:
            - app-network
        environment:
            PHP_IDE_CONFIG: serverName=alleynote

    nginx:
        image: nginx:stable-alpine
        ports:
            - '8888:80'
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
