version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: alleynote_web
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./database:/var/www/html/database
    networks:
      - alleynote-network

  nginx:
    image: nginx:alpine
    container_name: alleynote_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl.conf:/etc/nginx/conf.d/ssl.conf
      - ./ssl-data:/etc/letsencrypt
      - ./certbot-data:/var/www/certbot
    depends_on:
      - web
    networks:
      - alleynote-network

  certbot:
    image: certbot/certbot
    container_name: alleynote_certbot
    restart: unless-stopped
    volumes:
      - ./ssl-data:/etc/letsencrypt
      - ./certbot-data:/var/www/certbot
    command: |
      sh -c "
        if [ ! -f /etc/letsencrypt/live/${SSL_DOMAIN:-localhost}/fullchain.pem ]; then
          echo '正在申請 SSL 憑證...';
          certbot certonly --webroot --webroot-path=/var/www/certbot \
            --email ${SSL_EMAIL:-admin@localhost} \
            --agree-tos --no-eff-email \
            --staging=${CERTBOT_STAGING:-true} \
            -d ${SSL_DOMAIN:-localhost} \
            ${SSL_WWW_DOMAIN:+-d www.${SSL_DOMAIN}};
        else
          echo 'SSL 憑證已存在，跳過申請步驟';
        fi;
        trap exit TERM;
        while :; do
          echo '檢查憑證續簽...';
          certbot renew --quiet;
          sleep 12h & wait \$\${!};
        done;
      "
    networks:
      - alleynote-network

  redis:
    image: redis:alpine
    container_name: alleynote_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - alleynote-network

# SQLite3 資料庫檔案將儲存在本地 database/ 目錄中

networks:
  alleynote-network:
    driver: bridge
